version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=doctor_mgmt_docker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5433:5432"

  web:
    build: .
    # Docker up hote hi server chal jaye uske liye command
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=doctor_mgmt_docker  
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_PORT=5432
    depends_on:
      - db

volumes:
  postgres_data: